### ISSUE TITLE
As a player, I want to know how many points I have scored so that I can feel accomplished

### ISSUE THREAD

**Issue by gage-langdon** [gage-langdon/covid-jam#3]
- The score should start at 0
 - 1 point per food eaten
 - The score should display at the top left of the game window

 - mock of the score location and styling. the score should grow to the left (never should cover the play area).
![image](https://user-images.githubusercontent.com/8952305/78511781-13b7eb00-7754-11ea-9748-10a9a1a0a0dd.png)

**Comment by Camrynlangdon** [comment]
roger

**Comment by Camrynlangdon** [comment]
Done
